### ISSUE TITLE
E471: Argument required: ^I^I^Iargadd

### ISSUE THREAD

**Issue by eco0414** [vifm/vifm.vim#11]
question:
$ touch a.txt && vim
:EditVifm
open file

"a.txt" [converted] 0L, 0C
Error detected while processing function <SNR>60_StartVifm..<SNR>60_HandleRunRes
ults:
line   56:
E471: Argument required: ^I^I^Iargadd
E471: Argument required: ^I^I^Iargadd

Is there a way to hide error messages?

request:
I would appreciate it if Add a "sort by inode".

**Comment by xaizek** [comment]
> Is there a way to hide error messages?

It's better to fix them. And it should be fixed now, thanks for the report! Your version of Vim just doesn't have working `:argadd` command without arguments.

> I would appreciate it if Add a "sort by inode".

Sorting criteria already contain some things that were unexpected for me, so not a big deal adding one more, but why one would want to sort by inode?

**Comment by eco0414** [comment]
> why one would want to sort by inode?

Because the order of the songs of my digital audio player looks the same as sorted by i-node.

**Comment by xaizek** [comment]
In case you're using development version, sorting by inode is in the master branch now.
