### ISSUE TITLE
How to install using pathogen?

### ISSUE THREAD

**Issue by cevhyruz** [vifm/vifm.vim#17]
This should have a readme for installing isn't it? I can't seem to install it properly using pathogen.

**Comment by xaizek** [comment]
Installation is not different than for any other plugin. Something like
```bash
git clone https://github.com/vifm/vifm.vim.git ~/.vim/bundle/vifm
```
should work fine. Why do you think it doesn't work for you?

**Comment by cevhyruz** [comment]
I'm using neovim and installed it with pathogen but I can't seem to access the help. so I figured I guess it's about the installtion

**Comment by xaizek** [comment]
I think you just missing help tags. As pathogen's README says:

```
Normally to generate documentation, Vim expects you to run :helptags on each
directory with documentation (e.g., :helptags ~/.vim/doc). Provided with
pathogen.vim is a :Helptags command that does this on every directory in your
'runtimepath'. If you really want to get crazy, you could even invoke Helptags
in your vimrc. I don't like to get crazy.
```

So try running `:Helptags` and see if that makes help work.

**Comment by cevhyruz** [comment]
Sorry I kind of skimmed that part.. It works now! Thanks for the awesome plugin btw.
