### ISSUE TITLE
On Windows 10/Gvim, CreateProcess failed

### ISSUE THREAD

**Issue by Melandel** [vifm/vifm.vim#30]
If I run vim in a shell, `:Vifm` works.

But if I run gvim directly (with the UI), `:Vifm` throws the following message:

```
Error detected while processing function <SNR>41_StartVifm: line 94
CreateProcess failed
```

Is it possible to run `:Vifm` from Gvim, without being in a terminal ?

I'm using vifm 0.10.1 with vim 8.1 (including patch 1-2197).

**Comment by xaizek** [comment]
Thanks, you found a bug. The latest version should work fine.

**Comment by Melandel** [comment]
Thank you for your quick answer!

**Comment by dipta10** [comment]
I'm still getting the same error. I'm using Gvim on Windows 10 and have the latest version of vifm for vim.
```
Error detected while processing function <SNR>67_StartVifm: line 78
CreateProcess failed
```

**Comment by xaizek** [comment]
`CreateProcess` appears if command doesn't exist. Check that the value of `g:vifm_exec` makes sense.
