### ISSUE TITLE
Error detected <SNR>56_StartVifm:

### ISSUE THREAD

**Issue by sQVe** [vifm/vifm.vim#33]
Hey :wave:,

Since a couple of days ago this plugin errors for me. As soon I use the `:Vifm` command it outputs: 

```text
:Vifm
Error detected while processing function <SNR>56_StartVifm:
line   87:
E89: vifm: edit will be killed(add ! to override)
Press ENTER or type command to continue
```
I have the following settings:

```text
" Disable netrw.
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1

" Vifm.
let g:vifm_replace_netrw = 1
let g:vifm_term = "term"
```

Give me a ping if I can provide any more information to help out. I'm pretty helpless without this plugin :heart:

**Comment by xaizek** [comment]
Hello,

thanks for the report, I believe it is fixed now.

**Comment by sQVe** [comment]
@xaizek Works fine now. Thank you for  the quick fix!
