### ISSUE TITLE
Does not play well with Startify

### ISSUE THREAD

**Issue by sQVe** [vifm/vifm.vim#34]
Hey :wave:,

I just tried https://github.com/mhinz/vim-startify and `vifm` does not work well with it. When opening `vifm` from the `startify` screen and closing `vifm` it errors with the following: 

```
Error detected while processing function 17:
line    4:
E86: Buffer 1 does not exist
Press ENTER or type command to continue
```

If this issue is more fitting for `startify` then just ping me! :pray:

**Comment by xaizek** [comment]
Hi,

I saw that line with seemingly incomplete condition several days ago, but couldn't make it fail and left as is. I think it's fixed now. Thanks!

**Comment by sQVe** [comment]
Works fine now! Thank you, as always, for a quick fix @xaizek.
