### ISSUE TITLE
Got non-zero code from vifm in neovim

### ISSUE THREAD

**Issue by artur-shaik** [vifm/vifm.vim#4]
Vifm just does not start in neovim. Any thoughts?

**Comment by xaizek** [comment]
I confirm the issue, but it's not related to the plugin, even `:!vifm` doesn't work there:
```
:!vifm

Terminal error.
shell returned 1
```
I guess this comes from neovim handling spawned processes incorrectly (`ioctl(0, TIOCGWINSZ, &ws)` call fails) and seems to be an issue on their side (if they emulate terminal, then there is something wrong with the emulation). Not 100% sure about it, but everything works fine outside neovim... (Maybe there is an option to work around this behaviour, I don't know.)

**Comment by xaizek** [comment]
Yeah, one can't even run neovim from neovim:
```
:!./nvim

Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...

Vim: Finished.
 [?1049h [H [J [?2004h [?1004h [8;24;80t [H [J [1;1H [1;1H [34h [?25h [?25l [?1002h [?1006h [H [J [1;1H [2;1H [m  [94m~                                                                                [3;1H~
shell returned 1
```

**Comment by artur-shaik** [comment]
Ou yeah, just realized that is limitation in neovim. There are some issues about this. Here is one: https://github.com/neovim/neovim/issues/1496.
And here workaround implemented for ranger: https://github.com/hut/ranger/issues/279. May be can be implemented for this plugin too?

**Comment by xaizek** [comment]
:-( that looks ugly... hope it's the only thing related to the plugin they broke there.

Thanks for the information, I'll try to make it work.

**Comment by artur-shaik** [comment]
That would be great.

And thanks, for vifm and plugin.

On 01-23 (04:16), xaizek wrote:
>    :-( that looks ugly... hope it's the only thing related to the plugin they
>    broke there.
> 
>    Thanks for the information, I'll try to make it work.
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/vifm/vifm.vim/issues/4#issuecomment-174180722
>    2. https://github.com/vifm/vifm.vim/issues/4#issuecomment-174180722

-- 
Best regards,
Artur Shaikhullin

**Comment by xaizek** [comment]
Should generally work now. At least one thing that's not working is error messages, they aren't printed from callback (once they got printed in a terminal... I didn't get why), don't see how to fix them, so leaving as is. One also might need to have `'hidden'` option enabled or opening terminal will fail.

**Comment by artur-shaik** [comment]
Nice. It works as expected. Thank you.
