### ISSUE TITLE
Impossible to find your vifm configuration directory

### ISSUE THREAD

**Issue by sajusat** [vifm/vifm.vim#43]
I am getting the following error when I installed the plugin. I installed the plugin using vim plug and I can see it is in the ~/.vim/plugin/ directory. When I start neovim I get the following error message in nvim 

> Impossible to find your vifm configuration directory. Launch vifm one time and try again.

Can someone help ?

**Comment by xaizek** [comment]
This line is from very old version of the plugin, so find out where it comes from and remove it (`:scriptnames` might help). Moreover neovim uses `~/.config/nvim` for configuration.

**Comment by sajusat** [comment]
Thank you so much. I looked at the path and realized that it was some other fork that I was installed.
I changed it to `vifm/vifm.vim` and there is no more warnings.
