### ISSUE TITLE
EditVifm command doesn't show files

### ISSUE THREAD

**Issue by jonmwood** [vifm/vifm.vim#45]
Hi, I've been following several tutorials to install vifm as I'm a newbie to Vim, but when I run the `:EditVifm` command with and without `~`, no files or errors appear, it's just a quick flash of the screen and then shows the blank file again. Am I missing a configuration somewhere? Does this have to do with setting a certain path or environment variable somewhere? I didn't see others do that in the tutorials I followed. Thanks in advance!

## Before entering the command
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/12825083/84748181-22e5c100-af6d-11ea-8450-cc72fe9d6ccb.png">

## After entering the command
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/12825083/84748121-0fd2f100-af6d-11ea-950b-da1c04281bc9.png">

**Comment by xaizek** [comment]
Hello.

You should at least get an error message. Try running `:messages` after `:EditVifm`, maybe it gets erased from the screen.

Can you run `vifm` in terminal without issues? Also check that versions of vifm and the plugin aren't very old (they might not work together when one is much older than the other).

**Comment by flimofly** [comment]
I have the same issue. No luck with the `:messages`, unfortunately.

**Comment by xaizek** [comment]
What about versions and is it Vim or neovim?

**Comment by flimofly** [comment]
Vim 8.2 (MacVim)
vifm version 0.10.1

**Comment by xaizek** [comment]
Please pick up latest changes from the `master` and see if any error messages appear now (check `:messages` too).

**Comment by ChrisGitIt** [comment]
Hi all,

it seems I have the same problem. I could make some further investigations and it seems there is a difference between the console MacVim (mvim) and the GUI MacVim.

When i start MacVim from console (mvim), everything is working as expected. But starting MacVim by, for example, opening files from Mac Finder => Starting MacVim => VIFM Startup results in Exit Code 1. 

Here is what i tried so far:
- I tried to remove some "silent" commands from the vfim.vim plugin, but it seems its all the same calls (mvim and MacVim).
- Checked if :terminal is somehow not available and started vifm from within vim terminal (mvim and MacVim)
- Changed values for vars $vifm_embed_split, $vifm_embed_term and $vifm_exec_args (mvim and MacVim)

Any hint how to further debug?

Bye the way: :messages output:
Error "function VifmExitCb[14]..<SNR>60_HandleRunResults":
Line    2:
Got non-zero code from vifm: 1     

Any feedback is greatly appreciate!

Greets,

Chris

**Comment by xaizek** [comment]
Hello Chris,

you could try adding `echomsg options` before
```vim
				keepalt let buf = term_start(['/bin/sh', '-c', termcmd], options)
```
and then posting relevant line from `:messages`. Your description and what you have tried suggests that `$TERM` might be empty while it's assumed (probably incorrectly) to not be empty in GUI Vim.

**Comment by ChrisGitIt** [comment]
Hi xaizek,

thanks for your feedback and tips. I have added
# echomsg term_start
# echomsg options

Here is the output:
`
-- {'curwin': 1, 'env': {'TERM': ''}, 'exit_cb': function('VifmExitCb', [{'split': 1, 'cwdjob': 0, 'listf': '/var/folders/gk/xncxfgw55nb5fdfzy4nll8q00000gn/T/vrdeWeW/3', 'typef': '/var/folders/gk/xncxfgw55nb5fdfzy4nll8q00000gn/T/vrdeWeW/4', 'editcmd': 'vsplit'}]), 'term_name': 'vifm: vsplit'}
`

And for comparison, a output of a working call
`
{'curwin': 1, 'env': {'TERM': 'xterm-256color'}, 'exit_cb': function('VifmExitCb', [{'split': 1, 'cwdjob': 0, 'listf': '/var/folders/gk/xncxfgw55nb5fdfzy4nll8q00000gn/T/vilcZsF/3', 'typef': '/var/folders/gk/xncxfgw55nb5fdfzy4nll8q00000gn/T/vilcZsF/4', 'editcmd': 'vsplit'}]), 'term_name': 'vifm: vsplit'} 
`

As you have guessed, the terminal does not seem to exists. I tried:
:let $TERM='xterm-256color'
in vim as mentioned here: https://github.com/macvim-dev/macvim/issues/879

This seem to do the trick. Do you know if I can set this variable in vimrc or .vifmrc by config? Could not find a way to automatically set this value.

Thanks for your help so far!

Greets,

Chris

**Comment by xaizek** [comment]
> Do you know if I can set this variable in vimrc or .vifmrc by config?

Yes, you can if you wish. However, plugin now handles empty `$TERM`. Thanks for helping to resolve this!

**Comment by ChrisGitIt** [comment]
@xaizek: Thank YOU for your support.
I just saw this issue several times and it seems to be associated with many GUIs for vim. Hopefully this problem gets resolved for all of them. Bye the way: Great Software. Took me a long way to get here, but finally everything falls into place with a good file manager (and integration).
