### ISSUE TITLE
Line numbers displayed besides vifm in neovim

### ISSUE THREAD

**Issue by mroavi** [vifm/vifm.vim#46]
I recently moved to neovim. I noticed that the line numbers are being displayed besides vifm:

![image](https://user-images.githubusercontent.com/19517248/86185705-45fc9d00-bb37-11ea-907e-d912681a9fc5.png)

This does not happen in plain vim. Any idea of how to avoid displaying them besides vifm?

**Comment by xaizek** [comment]
Try updating the plugin, I've added disabling of line numbers in vifm's buffer (I doubt someone wants them there).

**Comment by mroavi** [comment]
Problem solved. Thanks.
