### ISSUE TITLE
Indentlines

### ISSUE THREAD

**Issue by hoaxdream** [vifm/vifm.vim#49]
hi, i have problem together with the plugin [indentline](https://github.com/Yggdroot/indentLine) it shows indentline in :TabVifm

![indentlines](https://i.imgur.com/SFNr3Fw.png)

how can i disable this?

i tried:
```
let g:indentLine_fileTypeExclude = ['Vifm']
let g:vim_Vifm_conceal = 0
```
but it doesn't work..
for anyone can help, thank you.

Edit: i fix it by setting:
```
let g:indentLine_bufNameExclude = ["\[vifm\]*"]
```

**Comment by ahmadie** [comment]
or to disable any indentline for terminals

augroup terminalgrp
  autocmd TermOpen * nested :IndentLinesDisable
augroup END
