### ISSUE TITLE
The title of the vifm terminal is too long

### ISSUE THREAD

**Issue by randomizedthinking** [vifm/vifm.vim#5]
It is a small issue. The title of the vifm terminal is very long that it will push some useful information in the status line away from the screen. Of course, it is also not eye-candy. I wonder whether it is possible to send a command like

```
:file vifm
```

so the terminal buffer will have a short yet meaningful name.

**Comment by xaizek** [comment]
I don't really understand what you mean. Are you using neovim instead of normal Vim, this "terminal buffer" confuses me?

**Comment by randomizedthinking** [comment]
Sorry for the confusing... Yes, I am using neovim and the vifm is running inside a terminal buffer.

Also, just tested on vim: the problem mentioned only occurs on neovim.

**Comment by xaizek** [comment]
> Yes, I am using neovim

Just don't forget to mention this :-) It's not compatible with Vim in many ways, so it matters.

> the problem mentioned only occurs on neovim.

I see it now, but `:file` has a weird side-effect (a bug?) of duplicating terminal buffer (we can close the previous one, but this messes up `#`). Maybe there are other ways, I'll try to find them, but don't remember any builtin functions for renaming buffers and don't see how to setup custom title via `termopen()`.

**Comment by randomizedthinking** [comment]
I see... Thanks!

IMHO, running vifm in a terminal buffer seems not necessary. I like the vim way better in this particular case: it is cleaner and more straightforward. Users will be focused on selecting files, and vifm is such a powerful tool for doing that.

**Comment by xaizek** [comment]
> IMHO, running vifm in a terminal buffer seems not necessary.

I agree, but if I get it right, it's the only possible way in neovim, because `:!` and `system()` don't provide terminal to external command, which then fails right away.

**Comment by xaizek** [comment]
`keepalt` kinda prevents wrong behaviour, so added it. There are unloaded buffers left, but it seems like they aren't active at all (no corresponding process), so it should be fine.

**Comment by xaizek** [comment]
I assume this is fixed.
