### ISSUE TITLE
Choosing which directories to open with the Vifm command

### ISSUE THREAD

**Issue by sholland1** [vifm/vifm.vim#50]
Is there a way to get the Vifm command to open the directory of the file I am currently editing in one pane and the working directory of Vim in the other?

I think this behavior would be a good default.

**Comment by xaizek** [comment]
This seems to work:
```vim
:execute 'Vifm' fnameescape(expand('%:p:h')) fnameescape(getcwd())
```

**Comment by sholland1** [comment]
Yep. It works. Thanks.

**Comment by kelvinzhao** [comment]
I don't know about vimscript, but I found adding `nnoremap <leader>vv :Vifm 1<CR>` in vimrc file will work too.
