### ISSUE TITLE
Vifm - <SNR>32_HandleRunResults

### ISSUE THREAD

**Issue by wborbajr** [vifm/vifm.vim#53]
Hi, I'm tryng to run Vifm but I'm getting error.

**"Plugins**
Plug 'vifm/vifm'
Plug 'vifm/vifm.vim'

**"Running neovim and trying to activate I  got the error below.**
:Vifm

Error detected while processing function 13[13]..<SNR>32_HandleRunResults:
line    2:
Got non-zero code from vifm: 127
Press ENTER or type command to continue

**"Vim version**

:version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototy
pes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCL
UDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-21571-gjtb7k/neovim-0.4.4/build/config
 -I/tmp/neovim-20200808-21571-gjtb7k/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-21571-gjtb7k/neovim-0.4.4/deps-build/include -I/usr/inclu
de -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-21571-gjtb7k/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-21571-gjtb7k/neovim-0.4.4/b
uild/include
Compiled by brew@HighSierra

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"

Run :checkhealth for more info

**Comment by xaizek** [comment]
Hi,

error code of 127 usually means that `vifm` command is absent. Have you installed the application?

**Comment by wborbajr** [comment]
Thank you.
