### ISSUE TITLE
Error when any random terminal buffer is already opened in neovim

### ISSUE THREAD

**Issue by ahmadie** [vifm/vifm.vim#55]
this seems to only happen with kitty terminal

call plug#begin('~/.vim/plugged')
Plug 'vifm/vifm.vim'
call plug#end()
let mapleader =" "
nnoremap <leader>n :Vifm<CR>

in nvim type
:terminal
then <leader>n

Error - 
Error detected while processing function 132[13]..<SNR>72_HandleRunResults:                                                                                         
line    2:
Got non-zero code from vifm: 1
Press ENTER or type command to continue

**Comment by ahmadie** [comment]
I found the problem, actually left side will try to expand to current file, which in case of terminal would be something like term://~//25789:/bin, so I changed following lines:

`let ldir = (a:0 > 0) ? a:1 : expand('%:p:h')`
`let ldir = (a:0 > 0) ? a:1 : ''`

which solved the problem

or just use:
`nnoremap <silent> <leader>n :exec ':Vifm ' . getcwd()<cr>`
to avoid expand func

**Comment by xaizek** [comment]
Thanks!
