### ISSUE TITLE
Documentation is inaccessible with :help

### ISSUE THREAD

**Issue by paddor** [vifm/vifm.vim#59]
I guess it's due to the directory structure under `doc/`. I expect something like `:help vifm` to work.

**Comment by xaizek** [comment]
You need to generate tags using Vim's [`:helptags` command](https://vimhelp.org/helphelp.txt.html#%3Ahelptags). Enter `doc/` and run `:helptags .` in Vim.

**Comment by paddor** [comment]
Thanks. Clumsy me actually installed `vifm/vifm` as a Vim package instead of `vifm/vifm.vim`.
