### ISSUE TITLE
Error when trying to use Vifm in vim

### ISSUE THREAD

**Issue by azizn03** [vifm/vifm.vim#60]
I get the following error when I try to use any command like :Vifm

`Error detected while processing function <SNR>28_StartVifm[109]..<SNR>28_HandleRunResults:
line    2:
Got non-zero code from vifm: 127`

I placed the vim folder in ~/.vim/plugin

**Comment by xaizek** [comment]
`127` usually means "command not found". Have you installed Vifm itself?

**Comment by azizn03** [comment]
I do indeed. This line is in my .vimrc file

`Plug 'vifm/vifm.vim'`

**Comment by xaizek** [comment]
That's just the Vim plugin (this repo). You need to install the app itself (https://github.com/vifm/vifm) separately.

**Comment by azizn03** [comment]
ah I was under the impression the vim plugin was standalone.
