### ISSUE TITLE
Documentation is outdated, g:vifm is now g:vifm_exec

### ISSUE THREAD

**Issue by AtomToast** [vifm/vifm.vim#62]
I was looking to change the executable that vifm.vim uses in order to enable ueberzug previews also inside of vim.

However setting `g:vifm`, as mentioned inside of `vifm-plugin.txt` does not actually seem to affect anything. Only from scanning through the plugin code I found out that apparently it now is `g:vifm_exec`, which also worked in changing the executable used.

**Comment by xaizek** [comment]
It's not outdated (`g:vifm` has never existed), it's just wrong. Thanks!
