### ISSUE TITLE
Is it possible to use ueberzug in vifm.vim?

### ISSUE THREAD

**Issue by dylanpjx** [vifm/vifm.vim#63]
As the title mentions, is it possible to use vifm image preview with ueberzug within vim itself? The vifm img preview script mentioned is in this [arch wiki link](https://wiki.archlinux.org/title/Vifm#Using_vifmimg).

**Comment by xaizek** [comment]
If you point `g:vifm_exec` to the script:
```vim
let g:vifm_exec = expand('$HOME/.config/vifm/vifmrun')
```
It will work, however it won't account for Vim's window offset.

**Comment by xaizek** [comment]
I think this has been resolved.
