### ISSUE TITLE
bug when setting let g:vifm_replace_netrw=1

### ISSUE THREAD

**Issue by GummyGun** [vifm/vifm.vim#65]
when opening vim with `"vim ."` and having `"let g:vifm_replace_netrw=1"` colors of the open file don't load correctly and when the file gets closed it doesn't refresh the screen correctly
this is how it should look
![image](https://user-images.githubusercontent.com/62158708/125138916-234f7d80-e0d5-11eb-8efd-0c9fb36eb887.png)
this is how it loads
![image](https://user-images.githubusercontent.com/62158708/125138942-31050300-e0d5-11eb-82f0-4fc164b8ef47.png)
and this is how it ends up looking when vim is closed
![image](https://user-images.githubusercontent.com/62158708/125138966-40844c00-e0d5-11eb-85f0-7bb5bdab2655.png)
![image](https://user-images.githubusercontent.com/62158708/125139001-50039500-e0d5-11eb-8bb6-7b98ca14801d.png)

**Comment by xaizek** [comment]
Thanks for the report. I see this issue with my test user (basically no configuration), but not for the main one. Not sure yet why it happens and why not always.

**Comment by xaizek** [comment]
Setting
```vim
let g:vifm_embed_term = 1
```
fixes it. This isn't specific to Vifm, running `!less ~/.vimrc` on startup messes Vim up in exactly the same way.
