### ISSUE TITLE
Opening a file in grep dialog

### ISSUE THREAD

**Issue by sassanh** [vifm/vifm.vim#7]
I'm using `neovim`. If I grep something, and then hit `<cr>` on a file in opened dialog, it opens the file in a new instance of neovim inside the terminal inside the neovim (another neovim instance in neovim) though if I hit `<cr>` in main `vifm` window it opens it in the main neovim instance as expected.

**Comment by xaizek** [comment]
Opening file in a menu doesn't qualify as file picking and I'm not sure whether it should (imagine that you want to examine files before you pick one of them). You can always navigate to a file with <kbd>gf</kbd> and pick it then. To be fair, there is also <kbd>e</kbd> so even if <kbd>cr</kbd> is changed, one will be able to view file.

**Comment by sassanh** [comment]
After pressing `gf` is it possible to move back to grep dialog when i'm done?

**Comment by xaizek** [comment]
I thought you just want to pick the file :-) It's not possible without repeating the command now, but I [want such functionality](https://github.com/vifm/vifm/blob/8f2dd08644f379a7783e5a62bf3675a36c5bbac7/TODO#L50) for a set of menus (`:locate`, `:find`, `:grep`), but didn't get to implementing it.

**Comment by sassanh** [comment]
I see, as may have seen in `mc`, it offers such functionality with <kbd>M-?</kbd> and it's pretty useful to search something in a directory and study each case and get back to list of results.

**Comment by sassanh** [comment]
Wow, that todo list is huge, so we're gonna see a lot more on vifm in future.

**Comment by xaizek** [comment]
Now there is `:copen` command which reopens last menu that supports navigation on <kbd>&lt;cr&gt;</kbd>.
