### ISSUE TITLE
Feature request: `:PeditVim`

### ISSUE THREAD

**Issue by maujim** [vifm/vifm.vim#75]
Is it possible to add a `:PeditVim` command when inside vifm so that the selected file can be opened in a preview window in vim?

**Comment by xaizek** [comment]
You mean that it should run `:pedit` inside Vim? It can open only one file, just ignore the rest if multiple were selected?

**Comment by maujim** [comment]
Yes exactly. 

I don't know if its possible, but could you disallow using `:pedit` if multiple files are selected?Not sure about the implementation of the other commands like `VsplitVim` but it could
