### ISSUE TITLE
Can't replace netRW with Vifm in Neovim.

### ISSUE THREAD

**Issue by homie-desktop** [vifm/vifm.vim#77]
Hi, I'm having trouble replacing netRW with VIFM. However, when trying NERDTree and LF plugin, they work fine as intended. I've already tried the following to add to my `.vimrc` file. 

```
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
let g:vifm_replace_netrw = 1
```

But when I try to open a directory the following error occurs:

Error detected while processing function <SNR>24_HandleBufEnter:
line    2:
E86: Buffer 1 does not exist
Press ENTER or type command to continue

This happens when I try to use Vifm, but NERDTree and LF works fine replacing netRW as intended. I'd like to use VIFM as my main file manager, I've already uninstalled LF and NERDTree because VIFM suits my needs. Thanks!

**Comment by xaizek** [comment]
Hello,

> I've already tried the following to add to my `.vimrc` file.

Why `.vimrc`? I think you need to add these lines to `~/.config/nvim/init.vim`. Have you tried that?

**Comment by homie-desktop** [comment]
@xaizek just tried it, still doesn't work. Same error;
 
```
Error detected while processing function 24_HandleBufEnter:
line 2:
E86: Buffer 1 does not exist
Press ENTER or type command to continue
```

I'm confused, LF and NERDTree seems to work fine when I try to use them to replace netRW. But when I try with VIFM, I got this same error.

**Comment by xaizek** [comment]
Try changing line 413 in `plugin/vifm.vim` to this:
```vim
			if bufexists(0)
				buffer #
			else
				enew
			endif

```
and see if the error goes away.

**Comment by homie-desktop** [comment]
@xaizek thanks! it's working now. I did what you said and update my .vimrc file

![plugin-vifm vim](https://user-images.githubusercontent.com/60292566/149947058-ea8d9022-c26e-4888-b653-05645039c10f.jpg)

![vimrc-vifm](https://user-images.githubusercontent.com/60292566/149947079-5183d501-723e-4356-86f1-00a454e882ea.jpg)
 
Now I can fully utilize vim key bindings to my workflow! Thank you so much for the quick response and your time! 👍👍👍

**Comment by xaizek** [comment]
Thanks for testing. Everything works for me even without this change, I'll commit it then.
