### ISSUE TITLE
[ Question ] Will vifm.vim add Lua version?

### ISSUE THREAD

**Issue by NEX-S** [vifm/vifm.vim#84]
The Neovim dev team had mentioned that they wouldn't add any vimL9 support so the vimL might be too slow for neovim :( will vifm.vim add neovim's lua integration?

**Comment by xaizek** [comment]
> so the vimL might be too slow for neovim

Are they doing `sleep 1` per each `:command`? If no, it won't be slow by any measure. The plugin does only trivial processing of data.

I see no use of employing Lua here (definitely not for performance), but you can try alternative plugins like https://github.com/haolian9/reveal.nvim (not sure if there are others at the moment).
