### ISSUE TITLE
install notes for vim 8

### ISSUE THREAD

**Issue by clach04** [vifm/vifm.vim#89]
Once vifm was installed, I found it easier to install using vim 8 package (not tried with nvim):

    git clone https://github.com/vifm/vifm.vim.git ~/.vim/pack/bundle/start/vifm

where `bundle` is the existing plugin name space I have.

Worth a PR?

I happen to be on debian so vifm was a quick

    sudo apt install vifm

**Comment by xaizek** [comment]
> Worth a PR?

Feel free to send one or I can update the README.

**Comment by clach04** [comment]
https://github.com/vifm/vifm.vim/pull/90

**Comment by xaizek** [comment]
Thanks!
