### ISSUE TITLE
Move to another window

### ISSUE THREAD

**Issue by mb720** [vifm/vifm.vim#99]
Hi and thanks for vifm.vim!

When having two windows opened in a split in Neovim, I call `:Vifm` in one of them. Then, I'd like to go back to the other window with <kbd>Ctrl-w</kbd> <kbd>Ctrl-w</kbd>. But that changes the current directory in the Vifm window instead which is not what I want.

Is there a way to jump to the other windows when Vifm is opened in one of them?

**Comment by xaizek** [comment]
Hello.

This seems to require mappings in Neovim, like you can see [in here](https://www.reddit.com/r/neovim/comments/5usi1q/how_to_change_tab_or_window_once_in_terminal/).  If you add those, they will apply to all terminal buffers.  Vim doesn't pass <kbd>Ctrl-w</kbd> through by default and that works quite well.
